### PR TITLE
#177 CDC DDI-C added namespace ddi

### PR DESCRIPTION
**Pull request by katja-moilanen**
Few minor changes also to usage guidance.

### CODE REVIEW

**Review by matthew-morris-cessda — CHANGES_REQUESTED** [review]
The DDI 1.2.2 profiles are incorrect as elements beyond the root `codeBook` element are in the default namespace (i.e. ""), not in the `ddi` namespace. The DDI 2 profiles are correct.

**Comment by katja-moilanen** [comment]
Did I understand correctly @matthew-morris-cessda that the correct XPath e.g. for title would then be /ddi:codeBook/stdyDscr/citation/titlStmt/titl for DDI1.2.2 profiles?

**Comment by matthew-morris-cessda** [comment]
Yes, see https://github.com/cessda/cessda.cdc.osmh-indexer.cmm/blob/df71000b3cdbae46d65b81f28f598109ddf89e93/src/test/resources/xml/nesstar/synthetic_compliant_cmm_nesstar.xml#L15. `<docDscr xmlns="">` sets the namespace back to the default namespace.

**Comment by katja-moilanen** [comment]
The example does not seem to be valid DDI @matthew-morris-cessda . Should it be possible to validate (with success) not valid DDI documents with the 1.2.2 profile? If I change the XPaths to be like /ddi:codeBook/stdyDscr/citation/titlStmt/titl , I'm afraid that valid DDI 1.2.2 documents cannot be succesfully validated.

**Comment by matthew-morris-cessda** [comment]
The document represents what was received from NESSTAR endpoints. It is not valid DDI, but NESSTAR endpoints didn't send valid DDI.

**Review by matthew-morris-cessda — APPROVED** [review]
Thanks for the changes. This looks good to merge now.

**Pull request merged**
